[package]
name = "address_book_rest_api"
version = "0.1.0"
authors = ["SakaDream <bahaimt@gmail.com>"]

[dependencies]
rocket = "0.4.0"
diesel_migrations = "1.4.0"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
log = "0.4.6"
jsonwebtoken = "5.0.1"
bcrypt = "0.4.0"
time = "0.1.42"
dotenv = "0.13.0"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["diesel_postgres_pool", "json"]

[dependencies.diesel]
version = "1.4.2"
features = ["postgres", "r2d2", "chrono"]

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]

[dependencies.uuid]
version = "0.7.4"
features = ["v4"]